In [1]:
import tensorflow as tf
from tensorflow.keras import layers
from keras.layers import BatchNormalization
from tensorflow import keras

In [2]:
model=keras.Sequential()

In [3]:
model.add(keras.layers.Dense(64,input_dim=14))

In [19]:
model.add(keras.layers.Dense(32,activation='selu'))

In [20]:
model.weights

[<tf.Variable 'dense/kernel:0' shape=(14, 64) dtype=float32, numpy=
 array([[ 2.70501047e-01, -1.39357463e-01,  1.19808674e-01,
         -2.37192929e-01,  7.98744857e-02, -3.38517874e-02,
          1.23099685e-02, -1.41717210e-01,  1.30229980e-01,
         -1.04957238e-01, -9.53710973e-02, -2.77995169e-02,
         -2.42921963e-01,  6.68635666e-02, -1.12619847e-01,
          5.65112531e-02,  8.72385502e-03,  1.96226060e-01,
          1.84375644e-01,  2.71175951e-01, -1.20145842e-01,
         -2.44366869e-01,  2.54948437e-02, -5.28320968e-02,
         -1.38960376e-01, -2.74675459e-01, -2.09483325e-01,
         -2.03798741e-01, -2.47682005e-01, -1.73571408e-02,
         -2.61060953e-01,  2.69036084e-01, -2.52696693e-01,
          1.36346430e-01,  2.15142608e-01, -2.19451815e-01,
          1.87514156e-01, -9.63896960e-02,  3.04163694e-02,
         -2.64923334e-01, -2.74933219e-01, -8.12250376e-03,
         -7.85995722e-02, -2.05031037e-01,  1.22239321e-01,
          2.37554580e-01,  2.294

In [21]:
model.add(tf.keras.layers.BatchNormalization(epsilon=0.00002))

In [22]:
model.weights

[<tf.Variable 'dense/kernel:0' shape=(14, 64) dtype=float32, numpy=
 array([[ 2.70501047e-01, -1.39357463e-01,  1.19808674e-01,
         -2.37192929e-01,  7.98744857e-02, -3.38517874e-02,
          1.23099685e-02, -1.41717210e-01,  1.30229980e-01,
         -1.04957238e-01, -9.53710973e-02, -2.77995169e-02,
         -2.42921963e-01,  6.68635666e-02, -1.12619847e-01,
          5.65112531e-02,  8.72385502e-03,  1.96226060e-01,
          1.84375644e-01,  2.71175951e-01, -1.20145842e-01,
         -2.44366869e-01,  2.54948437e-02, -5.28320968e-02,
         -1.38960376e-01, -2.74675459e-01, -2.09483325e-01,
         -2.03798741e-01, -2.47682005e-01, -1.73571408e-02,
         -2.61060953e-01,  2.69036084e-01, -2.52696693e-01,
          1.36346430e-01,  2.15142608e-01, -2.19451815e-01,
          1.87514156e-01, -9.63896960e-02,  3.04163694e-02,
         -2.64923334e-01, -2.74933219e-01, -8.12250376e-03,
         -7.85995722e-02, -2.05031037e-01,  1.22239321e-01,
          2.37554580e-01,  2.294

In [23]:
model.add(keras.layers.Dense(1))

In [24]:
model.weights

[<tf.Variable 'dense/kernel:0' shape=(14, 64) dtype=float32, numpy=
 array([[ 2.70501047e-01, -1.39357463e-01,  1.19808674e-01,
         -2.37192929e-01,  7.98744857e-02, -3.38517874e-02,
          1.23099685e-02, -1.41717210e-01,  1.30229980e-01,
         -1.04957238e-01, -9.53710973e-02, -2.77995169e-02,
         -2.42921963e-01,  6.68635666e-02, -1.12619847e-01,
          5.65112531e-02,  8.72385502e-03,  1.96226060e-01,
          1.84375644e-01,  2.71175951e-01, -1.20145842e-01,
         -2.44366869e-01,  2.54948437e-02, -5.28320968e-02,
         -1.38960376e-01, -2.74675459e-01, -2.09483325e-01,
         -2.03798741e-01, -2.47682005e-01, -1.73571408e-02,
         -2.61060953e-01,  2.69036084e-01, -2.52696693e-01,
          1.36346430e-01,  2.15142608e-01, -2.19451815e-01,
          1.87514156e-01, -9.63896960e-02,  3.04163694e-02,
         -2.64923334e-01, -2.74933219e-01, -8.12250376e-03,
         -7.85995722e-02, -2.05031037e-01,  1.22239321e-01,
          2.37554580e-01,  2.294